-- Seed a real sample published job for Jobs CRUD validation

insert into jobs (
  id,
  title,
  slug,
  organization,
  category,
  job_type,
  location,
  qualification,
  experience,
  salary,
  application_start_date,
  last_date,
  official_website,
  apply_link,
  short_description,
  full_description,
  application_fee,
  tags,
  featured,
  status,
  seo_title,
  seo_description,
  canonical_url,
  created_at,
  updated_at
) values (
  '99999999-9999-4999-9999-999999999999',
  'SSC CGL Recruitment 2026',
  'ssc-cgl-recruitment-2026',
  'Staff Selection Commission (SSC)',
  'Government Jobs',
  'Full Time',
  'India',
  'Bachelor Degree',
  'Freshers Eligible',
  '₹35,000 – ₹65,000',
  '2026-06-01',
  '2026-07-15',
  'https://ssc.gov.in',
  'https://ssc.gov.in',
  'Apply online for SSC CGL Recruitment 2026 for multiple central government posts across India.',
  'The Staff Selection Commission has released the SSC CGL Recruitment 2026 notification for various Group B and Group C posts. Eligible candidates can apply online before the last date.',
  '₹100',
  '["ssc","cgl","government-jobs","central-government","freshers"]',
  true,
  'published',
  'SSC CGL Recruitment 2026 Apply Online',
  'Apply online for SSC CGL Recruitment 2026. Check eligibility, salary, important dates, and application details.',
  null,
  now(),
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  organization = excluded.organization,
  category = excluded.category,
  job_type = excluded.job_type,
  location = excluded.location,
  qualification = excluded.qualification,
  experience = excluded.experience,
  salary = excluded.salary,
  application_start_date = excluded.application_start_date,
  last_date = excluded.last_date,
  official_website = excluded.official_website,
  apply_link = excluded.apply_link,
  short_description = excluded.short_description,
  full_description = excluded.full_description,
  application_fee = excluded.application_fee,
  tags = excluded.tags,
  featured = excluded.featured,
  status = excluded.status,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  canonical_url = excluded.canonical_url,
  updated_at = now();
